

export function commentsRecapPrompt(comments: string) {
  return `
        You are an e-commerce AI assistant. Read the following recent user comments about a product.
        Write a concise, 1-paragraph summary of the overall sentiment and main points. Do not use bullet points.
        Do not use any special characters.
        Dont use quotes.
        Dont use emojis.
        Dont say anything about the summary being generated by AI.
        Dont say anything except the summary.
        Maximum 50 words.
        At the end of the summary, say this product is good for whom.
        Recent Comments:
        ${comments}
      `;
}