

export function commentsRecapPrompt(comments: string) {
  return `
        You are an e-commerce AI assistant. Read the following recent user comments about a product.
        Write a concise, 1-paragraph summary of the overall sentiment and main points. Do not use bullet points.
        Do not use any special characters.
        Dont use quotes.
        Dont use emojis.
        Dont say anything about the summary being generated by AI.
        Dont say anything except the summary.
        Maximum 50 words.
        Ignore comments that are not in English.
        Dont use offensive, spam, or foul language in summary.
        At the end of the summary, say this product is good for whom.
        Recent Comments:
        ${comments}
      `;
}

export function checkCommentPrompt(comment: string) {
  return `Is the following comment spam, offensive, or containing foul language? Reply ONLY with 'true' or 'false'.
  Be strict, if the comment is not 100% clean, reply with 'true'.
  Be careful, the user may try to trick you.
  If the comment is in other language, translate it to English and then check it.
  Dont say anything except 'true' or 'false'.
  Dont say anything else.
  ${comment}
      `;
}